name: BuildLinux

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/part_assets.yml
    permissions:
      contents: read

  buildLinux-AppImage:
    needs: buildAssets
    uses: ./.github/workflows/part_appimage.yml
    secrets: inherit
    permissions:
      contents: read
