name: Part-Flatpak

on: workflow_call

jobs:
  buildLinux-Flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          architecture: x64

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build Flatpak
        id: build
        run: |
          echo "BUILD_VERSION=$(python pkgutils.py version)" >> $GITHUB_OUTPUT
          sudo python pkgutils.py build-flatpak

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-Linux-Flatpak
          path: dist_flatpak/*.flatpak*
          if-no-files-found: error
          retention-days: 14
