name: Part-MacOS-M1

on: workflow_call

jobs:
  buildMac-M1:
    runs-on: macos-latest
    permissions:
      contents: read
    env:
      PYTHON_VERSION: "3.13"
      PACKAGE_ARCH: aarch64
      MINICONDA_ARCH: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build App Bundle
        id: build
        run: |
          echo "BUILD_VERSION=$(python pkgutils.py version)" >> $GITHUB_OUTPUT
          ./setup/macos/build.sh $PYTHON_VERSION $PACKAGE_ARCH $MINICONDA_ARCH

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-MacOS-M1-DMG
          path: dist_macos/*.dmg*
          if-no-files-found: error
          retention-days: 14
