name: MacOS

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  testMac:
    runs-on: macos-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Install UV and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Sync UV
        run: |
          uv sync --verbose --no-dev --group test --group macos --python-platform x86_64-apple-darwin

      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          uv run --no-sync coverage run -m pytest -v --timeout=60
          uv run --no-sync coverage xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
